multilayer perceptron is the the simplest type of ANN().Each MLP model has an input layer,output layer and hidden layers.The hidden layers are activated by activation functions like ReLu,sigmoid ,tanh,identity functions.These perceptrons in the layers are highly connected and parallel,this accelerates the computation

In [ ]:
import pandas as pd
data=pd.read_csv('/content/HR_comma_sep.csv')
data.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

preprocessing :Label encoding ,map the salary column value: low:0,medium:1 and high:2 .This is label encoding

In [ ]:
#import label encoder
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
data['salary']=le.fit_transform(data['salary'])

In [ ]:
data.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,1
1,0.80,0.86,5,262,6,0,1,0,sales,2
2,0.11,0.88,7,272,4,0,1,0,sales,2
3,0.72,0.87,5,223,5,0,1,0,sales,1
4,0.37,0.52,2,159,3,0,1,0,sales,1

In [ ]:
X=data[['salary','satisfaction_level','last_evaluation','number_project','average_montly_hours','time_spend_company','Work_accident','promotion_last_5years']]
y=data['left']

In [ ]:
#train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

build employee churn using MLP classifier

In [ ]:
#import MLP classifier
from sklearn.neural_network import MLPClassifier
clf=MLPClassifier(hidden_layer_sizes=(6,5),random_state=42,verbose=True,learning_rate_init=0.01)
clf.fit(X_train,y_train)

Iteration 1, loss = 1.14754197
Iteration 2, loss = 0.59174127
Iteration 3, loss = 0.56460620
Iteration 4, loss = 0.53545601
Iteration 5, loss = 0.49659884
Iteration 6, loss = 0.44482426
Iteration 7, loss = 0.39563678
Iteration 8, loss = 0.35397231
Iteration 9, loss = 0.34581570
Iteration 10, loss = 0.32159180
Iteration 11, loss = 0.31172068
Iteration 12, loss = 0.30661609
Iteration 13, loss = 0.30961559
Iteration 14, loss = 0.29692430
Iteration 15, loss = 0.28178213
Iteration 16, loss = 0.28102957
Iteration 17, loss = 0.30100947
Iteration 18, loss = 0.27722131
Iteration 19, loss = 0.27176918
Iteration 20, loss = 0.27151673
Iteration 21, loss = 0.27854075
Iteration 22, loss = 0.27172229
Iteration 23, loss = 0.28242485
Iteration 24, loss = 0.27707414
Iteration 25, loss = 0.26332113
Iteration 26, loss = 0.28502039
Iteration 27, loss = 0.27144700
Iteration 28, loss = 0.26894862
Iteration 29, loss = 0.26683518
Iteration 30, loss = 0.27481583
Iteration 31, loss = 0.28203282
Iteration 32, loss = 0.27019496
Iteration 33, loss = 0.26584425
Iteration 34, loss = 0.27309692
Iteration 35, loss = 0.26921304
Iteration 36, loss = 0.25931996
Iteration 37, loss = 0.26155974
Iteration 38, loss = 0.29767165
Iteration 39, loss = 0.26671019
Iteration 40, loss = 0.25919419
Iteration 41, loss = 0.26815340
Iteration 42, loss = 0.26805928
Iteration 43, loss = 0.26994667
Iteration 44, loss = 0.26080826
Iteration 45, loss = 0.26514911
Iteration 46, loss = 0.27442328
Iteration 47, loss = 0.25914603
Iteration 48, loss = 0.25022106
Iteration 49, loss = 0.25538200
Iteration 50, loss = 0.25146902
Iteration 51, loss = 0.25582909
Iteration 52, loss = 0.25530455
Iteration 53, loss = 0.24267114
Iteration 54, loss = 0.25691082
Iteration 55, loss = 0.25187481
Iteration 56, loss = 0.24185904
Iteration 57, loss = 0.27780838
Iteration 58, loss = 0.30358536
Iteration 59, loss = 0.24107633
Iteration 60, loss = 0.24683463
Iteration 61, loss = 0.24851942
Iteration 62, loss = 0.24409659
Iteration 63, loss = 0.24799109
Iteration 64, loss = 0.24972489
Iteration 65, loss = 0.25136306
Iteration 66, loss = 0.26721329
Iteration 67, loss = 0.23642991
Iteration 68, loss = 0.24529533
Iteration 69, loss = 0.25199867
Iteration 70, loss = 0.23997386
Iteration 71, loss = 0.26948935
Iteration 72, loss = 0.24573041
Iteration 73, loss = 0.24705808
Iteration 74, loss = 0.23704245
Iteration 75, loss = 0.23433859
Iteration 76, loss = 0.25106192
Iteration 77, loss = 0.24286569
Iteration 78, loss = 0.23901147
Iteration 79, loss = 0.24213193
Iteration 80, loss = 0.24369163
Iteration 81, loss = 0.25732687
Iteration 82, loss = 0.23941355
Iteration 83, loss = 0.24097799
Iteration 84, loss = 0.25631296
Iteration 85, loss = 0.24206877
Iteration 86, loss = 0.23434115
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(hidden_layer_sizes=(6, 5), learning_rate_init=0.01,
              random_state=42, verbose=True)

verbose:is used to print progress messages to standard output hidden_layer_sizes=(6,5) 6 hidden layers with 5 neurons learning_rate:step size random_state=the initial random values for weights and for bias

In [ ]:
y_pred=clf.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8771111111111111